namespace gestor_bdm
{
    partial class generador_OI
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        private MetroFramework.Components.MetroStyleManager metroStyleManager1;
        private MetroFramework.Controls.MetroTile generar_OI;
        private MetroFramework.Controls.MetroTabControl metroTabControl1;
        private MetroFramework.Controls.MetroTabPage metroTabPage1;
        private MetroFramework.Controls.MetroTabPage metroTabPage2;
        private System.Windows.Forms.GroupBox groupBox1;
        private MetroFramework.Controls.MetroTextBox OI_text;
        private MetroFramework.Controls.MetroLabel metroLabel2;
        private MetroFramework.Controls.MetroLabel metroLabel1;
        private MetroFramework.Controls.MetroDateTime fechaFirma_text;
        private MetroFramework.Controls.MetroDateTime vigenciaDesde_text;
        private MetroFramework.Controls.MetroLabel metroLabel3;
        private MetroFramework.Controls.MetroDateTime vigenciaHasta_text;
        private MetroFramework.Controls.MetroLabel metroLabel4;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.GroupBox groupBox15;
        private System.Windows.Forms.GroupBox groupBox14;
        private System.Windows.Forms.GroupBox groupBox13;
        private System.Windows.Forms.GroupBox groupBox12;
        private System.Windows.Forms.GroupBox groupBox18;
        private MetroFramework.Controls.MetroTextBox clienteRazon;
        private MetroFramework.Controls.MetroLabel lanbel9999;
        private MetroFramework.Controls.MetroTextBox clienteComercial;
        private MetroFramework.Controls.MetroLabel metroLabel5;
        private MetroFramework.Controls.MetroTextBox clienteID;
        private MetroFramework.Controls.MetroLabel metroLabel6;
        private MetroFramework.Controls.MetroTextBox clientePostal;
        private MetroFramework.Controls.MetroLabel metroLabel10;
        private MetroFramework.Controls.MetroTextBox clientePais;
        private MetroFramework.Controls.MetroTextBox clienteCalle;
        private MetroFramework.Controls.MetroLabel metroLabel9;
        private MetroFramework.Controls.MetroLabel metroLabel8;
        private MetroFramework.Controls.MetroLabel metroLabel7;
        private MetroFramework.Controls.MetroTextBox cxpNombre;
        private MetroFramework.Controls.MetroLabel metroLabel11;
        private MetroFramework.Controls.MetroTextBox cxpCorreo;
        private MetroFramework.Controls.MetroLabel metroLabel13;
        private MetroFramework.Controls.MetroTextBox cxpTelefono;
        private MetroFramework.Controls.MetroLabel metroLabel12;
        private MetroFramework.Controls.MetroTextBox CComercial;
        private MetroFramework.Controls.MetroLabel metroLabel14;
        private MetroFramework.Controls.MetroTextBox TComercial;
        private MetroFramework.Controls.MetroLabel metroLabel15;
        private MetroFramework.Controls.MetroTextBox NComercial;
        private MetroFramework.Controls.MetroLabel metroLabel16;
        private MetroFramework.Controls.MetroTextBox PCorreo;
        private MetroFramework.Controls.MetroLabel metroLabel17;
        private MetroFramework.Controls.MetroTextBox PTelefono;
        private MetroFramework.Controls.MetroLabel metroLabel18;
        private MetroFramework.Controls.MetroTextBox PNombre;
        private MetroFramework.Controls.MetroLabel metroLabel19;
        private MetroFramework.Controls.MetroTextBox HCorreo;
        private MetroFramework.Controls.MetroLabel metroLabel20;
        private MetroFramework.Controls.MetroTextBox HTelefono;
        private MetroFramework.Controls.MetroLabel metroLabel21;
        private MetroFramework.Controls.MetroTextBox HNombre;
        private MetroFramework.Controls.MetroLabel metroLabel22;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.GroupBox groupBox5;
        private MetroFramework.Controls.MetroTextBox mediaPCorreo;
        private MetroFramework.Controls.MetroLabel metroLabel26;
        private MetroFramework.Controls.MetroTextBox mediaPTelefono;
        private MetroFramework.Controls.MetroLabel metroLabel27;
        private MetroFramework.Controls.MetroTextBox mediaPNombre;
        private MetroFramework.Controls.MetroLabel metroLabel28;
        private System.Windows.Forms.GroupBox groupBox6;
        private MetroFramework.Controls.MetroTextBox mediaCCorreo;
        private MetroFramework.Controls.MetroLabel metroLabel29;
        private MetroFramework.Controls.MetroTextBox mediaCTelefono;
        private MetroFramework.Controls.MetroLabel metroLabel30;
        private MetroFramework.Controls.MetroTextBox mediaCNombre;
        private MetroFramework.Controls.MetroLabel metroLabel31;
        private System.Windows.Forms.GroupBox groupBox7;
        private MetroFramework.Controls.MetroTextBox metroTextBox10;
        private MetroFramework.Controls.MetroLabel metroLabel32;
        private MetroFramework.Controls.MetroTextBox metroTextBox11;
        private MetroFramework.Controls.MetroTextBox metroTextBox12;
        private MetroFramework.Controls.MetroLabel metroLabel33;
        private MetroFramework.Controls.MetroLabel metroLabel34;
        private MetroFramework.Controls.MetroLabel metroLabel35;
        private MetroFramework.Controls.MetroTextBox metroTextBox13;
        private MetroFramework.Controls.MetroLabel metroLabel36;
        private MetroFramework.Controls.MetroTextBox metroTextBox14;
        private MetroFramework.Controls.MetroLabel metroLabel37;
        private System.Windows.Forms.GroupBox groupBox8;
        private MetroFramework.Controls.MetroTextBox cxcCorreo;
        private MetroFramework.Controls.MetroLabel metroLabel39;
        private MetroFramework.Controls.MetroTextBox cxcTelefono;
        private MetroFramework.Controls.MetroLabel metroLabel40;
        private MetroFramework.Controls.MetroTextBox cxcNombre;
        private MetroFramework.Controls.MetroLabel metroLabel41;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.GroupBox groupBox21;
        private Syncfusion.Windows.Forms.Tools.DoubleTextBox textDocDic;
        private Syncfusion.Windows.Forms.Tools.DoubleTextBox textDocNov;
        private Syncfusion.Windows.Forms.Tools.DoubleTextBox textDocOct;
        private Syncfusion.Windows.Forms.Tools.DoubleTextBox textDocSep;
        private Syncfusion.Windows.Forms.Tools.DoubleTextBox textDocAgo;
        private Syncfusion.Windows.Forms.Tools.DoubleTextBox textDocJul;
        private Syncfusion.Windows.Forms.Tools.DoubleTextBox textDocJun;
        private Syncfusion.Windows.Forms.Tools.DoubleTextBox textDocMay;
        private Syncfusion.Windows.Forms.Tools.DoubleTextBox textDocAbr;
        private Syncfusion.Windows.Forms.Tools.DoubleTextBox textDocMar;
        private Syncfusion.Windows.Forms.Tools.DoubleTextBox textDocFeb;
        private Syncfusion.Windows.Forms.Tools.DoubleTextBox textDocEne;
        private System.Windows.Forms.GroupBox groupBox20;
        private System.Windows.Forms.Label label37;
        private Syncfusion.Windows.Forms.Tools.DoubleTextBox porcentajeMF_box;
        private MetroFramework.Controls.MetroCheckBox checkBoxMF;
        private MetroFramework.Controls.MetroCheckBox checkFacturas;
        private MetroFramework.Controls.MetroCheckBox checkPagos;
        private MetroFramework.Controls.MetroCheckBox checkBancaria;
        private MetroFramework.Controls.MetroCheckBox checkProduccion;
        private MetroFramework.Controls.MetroLabel metroLabel38;
        private MetroFramework.Controls.MetroLabel metroLabel25;
        private MetroFramework.Controls.MetroDateTime dateTimeMF_hasta;
        private MetroFramework.Controls.MetroLabel metroLabel24;
        private MetroFramework.Controls.MetroDateTime dateTimeMF_desde;
        private MetroFramework.Controls.MetroLabel metroLabel23;
        private System.Windows.Forms.GroupBox groupBox9;
        private System.Windows.Forms.GroupBox groupBox10;
        private MetroFramework.Controls.MetroComboBox facturadoNov;
        private MetroFramework.Controls.MetroComboBox facturadoOct;
        private MetroFramework.Controls.MetroComboBox facturadoSep;
        private MetroFramework.Controls.MetroComboBox facturadoAgo;
        private MetroFramework.Controls.MetroComboBox facturadoJul;
        private MetroFramework.Controls.MetroComboBox facturadoJun;
        private MetroFramework.Controls.MetroComboBox facturadoMay;
        private MetroFramework.Controls.MetroComboBox facturadoAbr;
        private MetroFramework.Controls.MetroComboBox facturadoMar;
        private MetroFramework.Controls.MetroComboBox facturadoFeb;
        private MetroFramework.Controls.MetroComboBox facturadoEne;
        private MetroFramework.Controls.MetroComboBox facturadoDic;
        private MetroFramework.Controls.MetroLabel metroLabel43;
        private MetroFramework.Controls.MetroComboBox anioDic;
        private MetroFramework.Controls.MetroComboBox anioNov;
        private MetroFramework.Controls.MetroComboBox anioOct;
        private MetroFramework.Controls.MetroComboBox anioSep;
        private MetroFramework.Controls.MetroComboBox anioAgo;
        private MetroFramework.Controls.MetroComboBox anioJul;
        private MetroFramework.Controls.MetroComboBox anioJun;
        private MetroFramework.Controls.MetroComboBox anioMay;
        private MetroFramework.Controls.MetroComboBox anioAbr;
        private MetroFramework.Controls.MetroComboBox anioMar;
        private MetroFramework.Controls.MetroComboBox anioFeb;
        private MetroFramework.Controls.MetroComboBox anioEne;
        private MetroFramework.Controls.MetroLabel metroLabel42;
        private MetroFramework.Controls.MetroLabel metroLabel44;
        private MetroFramework.Controls.MetroLabel metroLabel45;
        private MetroFramework.Controls.MetroComboBox comboEne;
        private MetroFramework.Controls.MetroComboBox comboDic;
        private MetroFramework.Controls.MetroComboBox comboNov;
        private MetroFramework.Controls.MetroComboBox comboOct;
        private MetroFramework.Controls.MetroComboBox comboSep;
        private MetroFramework.Controls.MetroComboBox comboAgo;
        private MetroFramework.Controls.MetroComboBox comboJul;
        private MetroFramework.Controls.MetroComboBox comboJun;
        private MetroFramework.Controls.MetroComboBox comboMay;
        private MetroFramework.Controls.MetroComboBox comboAbr;
        private MetroFramework.Controls.MetroComboBox comboMar;
        private MetroFramework.Controls.MetroComboBox comboFeb;
        private MetroFramework.Controls.MetroLabel metroLabel46;
        private Syncfusion.WinForms.Input.SfNumericTextBox sfNumericTextBox1;
        private MetroFramework.Controls.MetroLabel metroLabel47;
        private MetroFramework.Controls.MetroTextBox metroTextBox8;
        private MetroFramework.Controls.MetroTextBox metroTextBox9;
        private MetroFramework.Controls.MetroTextBox metroTextBox15;
        private MetroFramework.Controls.MetroTextBox metroTextBox16;
        private MetroFramework.Controls.MetroTextBox metroTextBox4;
        private MetroFramework.Controls.MetroTextBox metroTextBox5;
        private MetroFramework.Controls.MetroTextBox metroTextBox6;
        private MetroFramework.Controls.MetroTextBox metroTextBox7;
        private MetroFramework.Controls.MetroTextBox metroTextBox2;
        private MetroFramework.Controls.MetroTextBox metroTextBox3;
        private MetroFramework.Controls.MetroTextBox metroTextBox1;
        private MetroFramework.Controls.MetroTextBox textBoxEne;
        private MetroFramework.Controls.MetroLabel metroLabel53;
        private MetroFramework.Controls.MetroLabel metroLabel54;
        private MetroFramework.Controls.MetroLabel metroLabel55;
        private MetroFramework.Controls.MetroTextBox textCargo_c;
        private MetroFramework.Controls.MetroTextBox textNombre_c;
        private MetroFramework.Controls.MetroLabel metroLabel52;
        private MetroFramework.Controls.MetroLabel metroLabel51;
        private MetroFramework.Controls.MetroLabel metroLabel50;
        private MetroFramework.Controls.MetroTextBox textCondiciones;
        private MetroFramework.Controls.MetroLabel metroLabel49;
        private MetroFramework.Controls.MetroCheckBox c_c_facturas;
        private MetroFramework.Controls.MetroCheckBox c_t_bancaria;
        private MetroFramework.Controls.MetroLabel metroLabel48;
        private MetroFramework.Controls.MetroButton Sumar;
        private MetroFramework.Controls.MetroTextBox textFechaCliente;
        private MetroFramework.Controls.MetroTextBox textFechaMedia;
        private MetroFramework.Controls.MetroTextBox textCargo_m;
        private MetroFramework.Controls.MetroTextBox textNombre_m;
        private System.Windows.Forms.PictureBox pictureBox1;
    }
}